### ISSUE TITLE
vcloud director usage

### ISSUE THREAD

**Issue by nlamirault** [vmware-archive/govcloudair#2]
It is possible tout use this library with vcloud director ?

**Comment by rickard-von-essen** [comment]
Currently no. But I have some patches to adapt it to also work with vcloud
director 5.5.

I can try and submit a PR for that next week.

**Comment by nlamirault** [comment]
great !

**Comment by frapposelli** [comment]
This project is currently aimed at vCloud Air only (currently supports subscription only but on-demand support is coming) and will focus solely on that.

That said, I have keen interest in having a vCloud Director Go SDK as well so please go ahead with your PR, Ideally I'd like to have a different repo for that but we can discuss it in the PR.

Thanks!

**Comment by mattbostock** [comment]
I'd also be interested in a vCloud Director client library in Go as a step towards a vCloud Director plugin for Terraform.

**Comment by rickard-von-essen** [comment]
You can try my adaptation to VDC 5.5 from this branch:
https://github.com/rickard-von-essen/govcloudair/tree/vcd-5.5
The code is of POC quality, and there is several things I would like to change before submitting a PR. Currently I have a hard time to say when I will have some time rewrite it.

Some of the things I would change is:
- Merge `api*.go`
- Merge the `VCDClient`, `VCAClient` and `Client` types
- Make all api calls check if they are working on VCD or VCA and handle this transparently from the client of the library.

It would be bad to have to different libraries for VCA and VCD since they are basically the same. If VMWare would opt for that I think there is room for a wrapper lib on top of those uniforming them, but that would be a lot of work for very little value. 

I have written a basic Packer VDC builder plugin that show that it is possible to use VCD with packer. The main obstacle to fix before I'll publish is to clean up the above code and to handle setup NAT for SSH into the VM.

@mattbostock I have yet not started to look into a vCloud plugin for Terraform. I will finish the packer plugin first. If you start to work on it be sure to ping me when you start and as soon as you have anything to show and I can contribute to.

**Comment by rickard-von-essen** [comment]
Also see #1

**Comment by frapposelli** [comment]
This is very good stuff, thanks @rickard-von-essen !

I don't particularly like the idea of having two separate libraries too, but with the launch of the vCloud Air On Demand service, the API extensions in vCA are more broad in scope than regular vCD API (which is still what lies underneath), I do have some ideas in mind, I will probably open up a proposal for discussion in the next days here on GH.

**Comment by nlamirault** [comment]
Great. We would like to use this library to manage our vCloud Director.

**Comment by bruceadowns** [comment]
I am also interested in using this (or similar) library to support vcd, onecloud, vcloudair, others. Was there a _proposal_ created to support this use-case as mentioned in previous comments? If so, I would like to review it.

**Comment by devopsbrett** [comment]
Thanks for the library, I also needed vcd support as I was developing a terraform vcd provider. I merged your work with that of @rickard-von-essen and added some features of my own. I've not opened a pull request as I couldn't guarantee the changes would be compatible with vCloudAir. My version, with changes, can be found here: https://github.com/opencredo/vmware-govcd

**Comment by nickithewatt** [comment]
@frapposelli just to add to @devopsbrett note above, we can certainly investigate if its worth bringing these changes back in here later, however it seems like vCloudAir and vCD are not guaranteed to stay compatible with each other and may warrant a separate repo anyway

**Comment by nickithewatt** [comment]
For those that are interested, here is the PR for the terraform-vcd-provider which makes use of the govcd fork https://github.com/hashicorp/terraform/pull/3785. Also please note that the forked repo being used for this PR is now https://github.com/hmrc/vmware-govcd not https://github.com/opencredo/vmware-govcd

**Comment by jkinred** [comment]
Has there been any further discussion on this topic?

I'm looking at vCloud Air provisioning with Terraform and have successfully provisioned a vApp with the Terraform vcd provider based on https://github.com/hmrc/vmware-govcd.

With the vcd Terraform provider landing on a public release (0.6.9) it seems like this is going to become more important as people start wanting to contribute upstream.

Is vCloud Air a superset of vCloud Director or will those products diverge too much to have a single library for both?

**Comment by frapposelli** [comment]
@jkinred vCloud Air is a superset of vCloud Director (at least for now), the library now supports both subscription and on demand APIs, I'm exploring the possibility to have support for plain vCloud Director in the library here, but that is yet to come.

I'm going to plan the roadmap for this and to support the Terraform providers officially, I'll update the thread once we reach a conclusion.

**Comment by casualjim** [comment]
@jkinred I'm looking at merging that fork into this library and having this library work with both vcloud and vcloudair.

**Comment by robcoward** [comment]
@casualjim how are you getting on with your merge ? If you are still working on it, I'm happy to assist, otherwise I'll take a crack at putting a PR together for a merge.

**Comment by frapposelli** [comment]
@robcoward we'll work on your PR #29

**Comment by robcoward** [comment]
Guess that this can be closed by #32

**Comment by frapposelli** [comment]
Thanks all, vCloud Director support has been merged now.
